name: Weekly Market Pulse
on:
  schedule:
    - cron: '0 16 * * 5' # Runs at 4 PM every Friday
  workflow_dispatch: # This allows us to "force" a run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Pulse Check
        run: python pulse_check.py